server:
  port: 8760

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb_zuul_security_jwt
    username: root
    password: rootroot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
        - id: produits
          uri: lb://microservice-produits
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://eureka-server
          predicates:
            - Path=/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9102/eureka/}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info