server:
  port: 8760

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-jwt
          uri: lb://microservice-jwt
          predicates:
             - Path=/microservice-jwt/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: eureka-server
          uri: lb://eureka-server
          predicates:
            - Path=/eureka-server/**
        - id: microservice-produits
          uri: lb://microservice-produits
          predicates:
            - Path=/microservice-produits/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9102/eureka/}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info